### ISSUE TITLE
时间同步那里没看懂，请问为什么相机去匹配雷达上一帧的数据就可以时间同步

### ISSUE THREAD

**Issue by lq17553049915** [xielock/Radar_Vision_Fusion#8]

**Comment by xielock** [comment]
这个是建立在我所使用的雷达和相机的采样频率基础上的，时间同步软同步即将各传感器数据统一到扫描周期较长（频率较小）的传感器数据上。我所采用的雷达采样频率更高，故建立了一个毫米波雷达数据队列，始终存储最新一帧的雷达数据，当相机数据来的时候，雷达最新一帧的数据就是最接近相机时间戳的数据。
